#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIRECTORY="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIRECTORY}/lib"

github_latest stripe/stripe-cli
