#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

exec 2>&1

SPACE_USER="${CLOR_SPACE_USER:-user}"
SPACE_HOME="${CLOR_SPACE_HOME:-/home/user}"
SPACE_PATH="${SPACE_HOME}/.local/bin:${SPACE_HOME}/go/bin:${SPACE_HOME}/.npm-global/bin:${PATH}"
SPACE_PLAYWRIGHT_BROWSERS_PATH="${SPACE_HOME}/.cache/ms-playwright"

exec gosu "${SPACE_USER}" env \
  HOME="${SPACE_HOME}" USER="${SPACE_USER}" LOGNAME="${SPACE_USER}" \
  PATH="${SPACE_PATH}" \
  PLAYWRIGHT_BROWSERS_PATH="${SPACE_PLAYWRIGHT_BROWSERS_PATH}" \
  websockify --web /usr/share/novnc 0.0.0.0:6080 127.0.0.1:5900
