#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

VERSION="$1"
ARCH="$(dpkg --print-architecture)"

ARCHIVE="/downloads/golangci-lint-${VERSION}-linux-${ARCH}.tar.gz"
URL="https://github.com/golangci/golangci-lint/releases/download/v${VERSION}/golangci-lint-${VERSION}-linux-${ARCH}.tar.gz"

if [[ ! -f "${ARCHIVE}" ]]; then
    curl --fail --silent --show-error --location \
        --output "${ARCHIVE}" "${URL}"
fi

EXTRACT_DIR="$(mktemp --directory)"
tar --extract --gzip \
    --directory="${EXTRACT_DIR}" \
    --file="${ARCHIVE}"
mv "${EXTRACT_DIR}/golangci-lint-${VERSION}-linux-${ARCH}/golangci-lint" \
    /usr/local/bin/
rm --recursive --force "${EXTRACT_DIR}"
