#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

stop_term() {
    printf 'term\n' >>/state/workload-child-signals
    exit 0
}

stop_int() {
    printf 'int\n' >>/state/workload-child-signals
    exit 0
}

trap stop_term TERM
trap stop_int INT
printf '%s' "$$" >/state/workload-child.pid
while :; do
    sleep 1
done
